"""initial schema

Revision ID: f96cf7661a66
Revises: 
Create Date: 2026-03-10 13:24:59.480717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96cf7661a66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_cases',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('expected_stance', sa.String(length=20), nullable=True),
    sa.Column('expected_score_min', sa.Float(), nullable=True),
    sa.Column('expected_score_max', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('analysis_mode', sa.String(length=50), nullable=False),
    sa.Column('time_horizon', sa.String(length=20), nullable=False),
    sa.Column('model_bundle_version', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_asset_id'), 'research_runs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_research_runs_status'), 'research_runs', ['status'], unique=False)
    op.create_table('agent_outputs',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('run_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('stance', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_results',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('eval_case_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('actual_stance', sa.String(length=20), nullable=True),
    sa.Column('actual_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('run_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['eval_case_id'], ['eval_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_signals',
    sa.Column('id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('run_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('final_stance', sa.String(length=20), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('final_confidence', sa.Float(), nullable=False),
    sa.Column('risk_override', sa.Boolean(), nullable=False),
    sa.Column('release_status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('contributing_agents', sa.JSON(), nullable=True),
    sa.Column('blocked_reasons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_final_signals_run_id')
    )
    op.create_index(op.f('ix_final_signals_release_status'), 'final_signals', ['release_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_final_signals_release_status'), table_name='final_signals')
    op.drop_table('final_signals')
    op.drop_table('eval_results')
    op.drop_table('agent_outputs')
    op.drop_index(op.f('ix_research_runs_status'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_asset_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_table('eval_cases')
    # ### end Alembic commands ###
